//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Requests
{
    using DingSDK.Models.Requests;
    using DingSDK.Utils;
    using System.Collections.Generic;
    
    public class LookupRequest
    {

        [SpeakeasyMetadata("header:style=simple,explode=false,name=customer-uuid")]
        public string CustomerUuid { get; set; } = default!;

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=phone_number")]
        public string PhoneNumber { get; set; } = default!;

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")]
        public List<DingSDK.Models.Requests.Type>? Type { get; set; }
    }
}