//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Requests
{
    using DingSDK.Utils;
    
    public class LookupRequest
    {

        [SpeakeasyMetadata("header:style=simple,explode=false,name=customer-uuid")]
        public string CustomerUuid { get; set; } = default!;

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=phone_number")]
        public string PhoneNumber { get; set; } = default!;
    }
}