//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Models.Components;
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public class Attempt
    {

        /// <summary>
        /// The attempt number.
        /// </summary>
        [JsonProperty("attempt_number")]
        public long? AttemptNumber { get; set; }

        /// <summary>
        /// The capability of the attempt.
        /// </summary>
        [JsonProperty("capability")]
        public Capability? Capability { get; set; }

        /// <summary>
        /// The content of the attempt.
        /// </summary>
        [JsonProperty("content")]
        public string? Content { get; set; }

        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The ID of the attempt.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The sender ID of the attempt.
        /// </summary>
        [JsonProperty("sender_id")]
        public string? SenderId { get; set; }

        /// <summary>
        /// The status of the attempt. Possible values are:<br/>
        /// 
        /// <remarks>
        ///   * `pending` - The attempt is pending.<br/>
        ///   * `delivered` - The attempt was delivered.<br/>
        ///   * `failed` - The attempt failed.<br/>
        ///   * `rate_limited` - The authentication was rate limited and cannot be retried.<br/>
        ///   * `expired` - The authentication has expired and cannot be retried.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("status")]
        public AuthenticationStatusResponseSchemasStatus? Status { get; set; }

        /// <summary>
        /// The type of the event.
        /// </summary>
        [JsonProperty("type")]
        public Models.Components.Type? Type { get; set; }
    }
}