//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of the event.
    /// </summary>
    public enum AuthenticationStatusResponseSchemasType
    {
        [JsonProperty("attempt")]
        Attempt,
        [JsonProperty("check")]
        Check,
        [JsonProperty("delivery_status")]
        DeliveryStatus,
        [JsonProperty("balance_update")]
        BalanceUpdate,
    }

    public static class AuthenticationStatusResponseSchemasTypeExtension
    {
        public static string Value(this AuthenticationStatusResponseSchemasType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AuthenticationStatusResponseSchemasType ToEnum(this string value)
        {
            foreach(var field in typeof(AuthenticationStatusResponseSchemasType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AuthenticationStatusResponseSchemasType)
                    {
                        return (AuthenticationStatusResponseSchemasType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AuthenticationStatusResponseSchemasType");
        }
    }

}