//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The status of the delivery. Possible values are:<br/>
    /// 
    /// <remarks>
    ///   * `unknown` - The status of the delivery is unknown.<br/>
    ///   * `submitted` - The message has been submitted to the carrier.<br/>
    ///   * `in_transit` - The message is in transit to the recipient.<br/>
    ///   * `delivered` - The message has been delivered to the recipient.<br/>
    ///   * `undeliverable` - The message could not be delivered to the recipient.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum AuthenticationStatusResponseStatus
    {
        [JsonProperty("unknown")]
        Unknown,
        [JsonProperty("submitted")]
        Submitted,
        [JsonProperty("in_transit")]
        InTransit,
        [JsonProperty("delivered")]
        Delivered,
        [JsonProperty("undeliverable")]
        Undeliverable,
    }

    public static class AuthenticationStatusResponseStatusExtension
    {
        public static string Value(this AuthenticationStatusResponseStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AuthenticationStatusResponseStatus ToEnum(this string value)
        {
            foreach(var field in typeof(AuthenticationStatusResponseStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AuthenticationStatusResponseStatus)
                    {
                        return (AuthenticationStatusResponseStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AuthenticationStatusResponseStatus");
        }
    }

}