//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The status of the attempt. Possible values are:<br/>
    /// 
    /// <remarks>
    ///   * `pending` - The attempt is pending.<br/>
    ///   * `delivered` - The attempt was delivered.<br/>
    ///   * `failed` - The attempt failed.<br/>
    ///   * `rate_limited` - The authentication was rate limited and cannot be retried.<br/>
    ///   * `expired` - The authentication has expired and cannot be retried.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum AuthenticationStatusResponseSchemasStatus
    {
        [JsonProperty("pending")]
        Pending,
        [JsonProperty("delivered")]
        Delivered,
        [JsonProperty("failed")]
        Failed,
        [JsonProperty("rate_limited")]
        RateLimited,
        [JsonProperty("expired")]
        Expired,
    }

    public static class AuthenticationStatusResponseSchemasStatusExtension
    {
        public static string Value(this AuthenticationStatusResponseSchemasStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AuthenticationStatusResponseSchemasStatus ToEnum(this string value)
        {
            foreach(var field in typeof(AuthenticationStatusResponseSchemasStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AuthenticationStatusResponseSchemasStatus)
                    {
                        return (AuthenticationStatusResponseSchemasStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AuthenticationStatusResponseSchemasStatus");
        }
    }

}