//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum BalanceUpdateType
    {
        [JsonProperty("unknown")]
        Unknown,
        [JsonProperty("authentication")]
        Authentication,
        [JsonProperty("attempt")]
        Attempt,
        [JsonProperty("attempt_pending")]
        AttemptPending,
        [JsonProperty("attempt_success")]
        AttemptSuccess,
        [JsonProperty("authentication_pending")]
        AuthenticationPending,
        [JsonProperty("authentication_success")]
        AuthenticationSuccess,
    }

    public static class BalanceUpdateTypeExtension
    {
        public static string Value(this BalanceUpdateType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static BalanceUpdateType ToEnum(this string value)
        {
            foreach(var field in typeof(BalanceUpdateType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is BalanceUpdateType)
                    {
                        return (BalanceUpdateType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum BalanceUpdateType");
        }
    }

}