//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The capability of the attempt.
    /// </summary>
    public enum Capability
    {
        [JsonProperty("rcs")]
        Rcs,
        [JsonProperty("text")]
        Text,
        [JsonProperty("whatsapp")]
        Whatsapp,
        [JsonProperty("viber")]
        Viber,
    }

    public static class CapabilityExtension
    {
        public static string Value(this Capability value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Capability ToEnum(this string value)
        {
            foreach(var field in typeof(Capability).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Capability)
                    {
                        return (Capability)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Capability");
        }
    }

}