
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using Newtonsoft.Json;
    
    public class CreateCheckResponse
    {

        /// <summary>
        /// The UUID of the corresponding authentication.
        /// </summary>
        [JsonProperty("authentication_uuid")]
        public string? AuthenticationUuid { get; set; }

        /// <summary>
        /// A status representing the result of the check.
        /// </summary>
        [JsonProperty("status")]
        public CreateCheckResponseStatus? Status { get; set; }
    }
}