//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    
    public class CreateCheckRequest
    {

        /// <summary>
        /// The authentication UUID that was returned when you created the authentication.
        /// </summary>
        [JsonProperty("authentication_uuid")]
        public string AuthenticationUuid { get; set; } = default!;

        /// <summary>
        /// The code that the user entered.
        /// </summary>
        [JsonProperty("check_code")]
        public string CheckCode { get; set; } = default!;

        /// <summary>
        /// Your customer UUID, which can be found in the API settings in the Dashboard.
        /// </summary>
        [JsonProperty("customer_uuid")]
        public string CustomerUuid { get; set; } = default!;
    }
}