//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Models.Components;
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public class DeliveryStatus
    {

        /// <summary>
        /// The ID of the attempt.
        /// </summary>
        [JsonProperty("attempt_id")]
        public string? AttemptId { get; set; }

        /// <summary>
        /// The attempt number.
        /// </summary>
        [JsonProperty("attempt_number")]
        public long? AttemptNumber { get; set; }

        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The status of the delivery. Possible values are:<br/>
        /// 
        /// <remarks>
        ///   * `unknown` - The status of the delivery is unknown.<br/>
        ///   * `submitted` - The message has been submitted to the carrier.<br/>
        ///   * `in_transit` - The message is in transit to the recipient.<br/>
        ///   * `delivered` - The message has been delivered to the recipient.<br/>
        ///   * `undeliverable` - The message could not be delivered to the recipient.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("status")]
        public AuthenticationStatusResponseStatus? Status { get; set; }

        /// <summary>
        /// The type of the event.
        /// </summary>
        [JsonProperty("type")]
        public AuthenticationStatusResponseSchemasType? Type { get; set; }
    }
}