
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of device the user is using.
    /// </summary>
    public enum DeviceType
    {
        [JsonProperty("IOS")]
        Ios,
        [JsonProperty("ANDROID")]
        Android,
        [JsonProperty("WEB")]
        Web,
    }

    public static class DeviceTypeExtension
    {
        public static string Value(this DeviceType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static DeviceType ToEnum(this string value)
        {
            foreach(var field in typeof(DeviceType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DeviceType)
                    {
                        return (DeviceType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DeviceType");
        }
    }

}