
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using Newtonsoft.Json;
    
    public class ErrorResponse
    {

        [JsonProperty("code")]
        public Code? Code { get; set; }

        /// <summary>
        /// A link to the documentation that describes the error.
        /// </summary>
        [JsonProperty("doc_url")]
        public string? DocUrl { get; set; }

        [JsonProperty("message")]
        public string? Message { get; set; }
    }
}