//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Models.Errors;
    using DingSDK.Utils;
    using Newtonsoft.Json;
    
    public class ErrorResponse
    {

        /// <summary>
        /// A machine-readable code that describes the error.
        /// </summary>
        [JsonProperty("code")]
        public Code? Code { get; set; }

        /// <summary>
        /// A link to the documentation that describes the error.
        /// </summary>
        [JsonProperty("doc_url")]
        public string? DocUrl { get; set; }

        /// <summary>
        /// A human-readable message that describes the error.
        /// </summary>
        [JsonProperty("message")]
        public string? Message { get; set; }
    }
}