
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of the feedback.
    /// </summary>
    public enum FeedbackRequestStatus
    {
        [JsonProperty("onboarded")]
        Onboarded,
        [JsonProperty("not_onboarded")]
        NotOnboarded,
    }

    public static class FeedbackRequestStatusExtension
    {
        public static string Value(this FeedbackRequestStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static FeedbackRequestStatus ToEnum(this string value)
        {
            foreach(var field in typeof(FeedbackRequestStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is FeedbackRequestStatus)
                    {
                        return (FeedbackRequestStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum FeedbackRequestStatus");
        }
    }

}