
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using Newtonsoft.Json;
    
    public class FeedbackResponse
    {

        /// <summary>
        /// The UUID of the feedback.
        /// </summary>
        [JsonProperty("uuid")]
        public string? Uuid { get; set; }
    }
}