
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using Newtonsoft.Json;
    
    public class LookupRequest
    {

        /// <summary>
        /// An E.164 formatted phone number to lookup.
        /// </summary>
        [JsonProperty("phone_number")]
        public string? PhoneNumber { get; set; }
    }
}