//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Models.Components;
    using DingSDK.Utils;
    using Newtonsoft.Json;
    
    public class LookupResponse
    {

        /// <summary>
        /// The carrier of the phone number.
        /// </summary>
        [JsonProperty("carrier")]
        public string? Carrier { get; set; }

        /// <summary>
        /// The ISO 3166-1 alpha-2 country code of the phone number.
        /// </summary>
        [JsonProperty("country_code")]
        public string? CountryCode { get; set; }

        /// <summary>
        /// The type of phone line.<br/>
        /// 
        /// <remarks>
        ///   * `CallingCards` - Numbers that are associated with providers of pre-paid domestic and international calling cards.<br/>
        ///   * `FixedLine` - Landline phone numbers.<br/>
        ///   * `InternetServiceProvider` - Numbers reserved for ISPs.<br/>
        ///   * `LocalRate` - Numbers that can be assigned non-geographically.<br/>
        ///   * `Mobile` - Mobile phone numbers.<br/>
        ///   * `Other` - Other types of services.<br/>
        ///   * `Pager` - Number ranges specifically allocated to paging devices.<br/>
        ///   * `PayPhone` - Allocated numbers for payphone kiosks in some countries.<br/>
        ///   * `PremiumRate` - Landline numbers where the calling party pays more than standard.<br/>
        ///   * `Satellite` - Satellite phone numbers.<br/>
        ///   * `Service` - Automated applications.<br/>
        ///   * `SharedCost` - Specific landline ranges where the cost of making the call is shared between the calling and called party.<br/>
        ///   * `ShortCodesCommercial` - Short codes are memorable, easy-to-use numbers, like the UK&apos;s NHS 111, often sold to businesses. Not available in all countries.<br/>
        ///   * `TollFree` - Number where the called party pays for the cost of the call not the calling party.<br/>
        ///   * `UniversalAccess` - Number ranges reserved for Universal Access initiatives.<br/>
        ///   * `Unknown` - Unknown phone number type.<br/>
        ///   * `VPN` - Numbers are used exclusively within a private telecommunications network, connecting the operator&apos;s terminals internally and not accessible via the public telephone network.<br/>
        ///   * `VoiceMail` - A specific category of Interactive Voice Response (IVR) services.<br/>
        ///   * `Voip` - Specific ranges for providers of VoIP services to allow incoming calls from the regular telephony network.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("line_type")]
        public LineType? LineType { get; set; }

        /// <summary>
        /// The mobile country code of the phone number.
        /// </summary>
        [JsonProperty("mcc")]
        public string? Mcc { get; set; }

        /// <summary>
        /// The mobile network code of the phone number.
        /// </summary>
        [JsonProperty("mnc")]
        public string? Mnc { get; set; }

        /// <summary>
        /// Whether the phone number has been ported.
        /// </summary>
        [JsonProperty("number_ported")]
        public bool? NumberPorted { get; set; }

        /// <summary>
        /// An E.164 formatted phone number.
        /// </summary>
        [JsonProperty("phone_number")]
        public string? PhoneNumber { get; set; }

        /// <summary>
        /// Whether the phone number is in our database of disposable, temporary phone numbers
        /// </summary>
        [JsonProperty("temporary_phone_number")]
        public bool? TemporaryPhoneNumber { get; set; }
    }
}