
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    
    public class RetryAuthenticationResponse
    {

        /// <summary>
        /// The UUID of the corresponding authentication.
        /// </summary>
        [JsonProperty("authentication_uuid")]
        public string? AuthenticationUuid { get; set; }

        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The time at which the next retry will be available.
        /// </summary>
        [JsonProperty("next_retry_at")]
        public DateTime? NextRetryAt { get; set; }

        /// <summary>
        /// The number of retries remaining.
        /// </summary>
        [JsonProperty("remaining_retry")]
        public long? RemainingRetry { get; set; }

        /// <summary>
        /// The status of the authentication.
        /// </summary>
        [JsonProperty("status")]
        public RetryAuthenticationResponseStatus? Status { get; set; }
    }
}