
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using Newtonsoft.Json;
    using System;
    
    public class RetryAuthenticationResponse
    {

        /// <summary>
        /// The UUID of the corresponding authentication.
        /// </summary>
        [JsonProperty("authentication_uuid")]
        public string? AuthenticationUuid { get; set; }

        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The time at which the next retry will be available.
        /// </summary>
        [JsonProperty("next_retry_at")]
        public DateTime? NextRetryAt { get; set; }

        /// <summary>
        /// The number of remaining retries.
        /// </summary>
        [JsonProperty("remaining_retry")]
        public long? RemainingRetry { get; set; }

        /// <summary>
        /// The status of the retry. Possible values are:<br/>
        /// 
        /// <remarks>
        ///   * `approved` - The retry was approved and a new code was sent.<br/>
        ///   * `denied` - The retry was denied.<br/>
        ///   * `no_attempt` - No attempt was sent yet, so a retry cannot be completed.<br/>
        ///   * `rate_limited` - The authentication was rate limited and cannot be retried.<br/>
        ///   * `expired_auth` - The authentication has expired and cannot be retried.<br/>
        ///   * `already_validated` - The authentication has already been validated.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("status")]
        public RetryAuthenticationResponseStatus? Status { get; set; }
    }
}