
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    
    public class RetryAuthenticationRequest
    {

        /// <summary>
        /// The authentication UUID that was returned when you created the authentication.
        /// </summary>
        [JsonProperty("authentication_uuid")]
        public string AuthenticationUuid { get; set; } = default!;

        /// <summary>
        /// Your customer UUID, which can be found in the API settings in the dashboard.
        /// </summary>
        [JsonProperty("customer_uuid")]
        public string CustomerUuid { get; set; } = default!;
    }
}