
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Components
{
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The status of the retry. Possible values are:<br/>
    /// 
    /// <remarks>
    ///   * `approved` - The retry was approved and a new code was sent.<br/>
    ///   * `denied` - The retry was denied.<br/>
    ///   * `no_attempt` - No attempt was sent yet, so a retry cannot be completed.<br/>
    ///   * `rate_limited` - The authentication was rate limited and cannot be retried.<br/>
    ///   * `expired_auth` - The authentication has expired and cannot be retried.<br/>
    ///   * `already_validated` - The authentication has already been validated.<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum RetryAuthenticationResponseStatus
    {
        [JsonProperty("approved")]
        Approved,
        [JsonProperty("denied")]
        Denied,
        [JsonProperty("no_attempt")]
        NoAttempt,
        [JsonProperty("rate_limited")]
        RateLimited,
        [JsonProperty("expired_auth")]
        ExpiredAuth,
        [JsonProperty("already_validated")]
        AlreadyValidated,
    }

    public static class RetryAuthenticationResponseStatusExtension
    {
        public static string Value(this RetryAuthenticationResponseStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static RetryAuthenticationResponseStatus ToEnum(this string value)
        {
            foreach(var field in typeof(RetryAuthenticationResponseStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is RetryAuthenticationResponseStatus)
                    {
                        return (RetryAuthenticationResponseStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum RetryAuthenticationResponseStatus");
        }
    }

}