//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DingSDK.Models.Errors
{
    using DingSDK.Models.Errors;
    using DingSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Bad Request
    /// </summary>
    public class ErrorResponse : Exception
    {

        /// <summary>
        /// A machine-readable code that describes the error.
        /// </summary>
        [JsonProperty("code")]
        public Code? Code { get; set; }

        /// <summary>
        /// A link to the documentation that describes the error.
        /// </summary>
        [JsonProperty("doc_url")]
        public string? DocUrl { get; set; }

        /// <summary>
        /// A human-readable message that describes the error.
        /// </summary>
        [JsonProperty("message")]
        private string? _message { get; set; }
        public override string Message { get {return _message ?? "";} }
    }
}