workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/ding-live/openapi/main/ding.yaml
        registry:
            location: registry.speakeasyapi.dev/ding/ding/my-source
targets:
    DingSDK:
        target: csharp
        source: my-source
        publish:
            nuget:
                apiKey: $NUGET_API_KEY
