name: Release Ding library
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force publication of SDK
        type: boolean
        default: false
  push:
    paths:
      - ./RELEASES.md
    branches:
      - main
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v14
    with:
      create_release: true
      publish_csharp: true
      force: ${{ github.event.inputs.force }}
      languages: |
        - csharp
      mode: direct
      openapi_docs: |
        - https://raw.githubusercontent.com/ding-live/openapi/main/ding.yaml
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
